# Generated by Django 4.1.7 on 2023-06-24 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, null=True)),
                ('damage_date', models.DateField(null=True)),
                ('damage_reason', models.TextField(null=True)),
                ('report_date', models.DateField(null=True)),
                ('check_notes', models.TextField(null=True)),
                ('Examination_officer_name', models.CharField(max_length=50, null=True)),
                ('nurse_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('clinic', models.CharField(max_length=50)),
                ('date_of_supply', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=50)),
                ('serial', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across\xa0whole\xa0library', primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('Eng_signature', models.CharField(max_length=50)),
                ('Company_signature', models.CharField(max_length=50)),
                ('device_condition', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('Responsible_party', models.CharField(max_length=50, null=True)),
                ('height', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('integrated_doctors', models.TextField(max_length=300, null=True)),
                ('surgical', models.TextField(max_length=300, null=True)),
                ('primary_diagnosis', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('university', models.CharField(max_length=50, null=True)),
                ('degree', models.CharField(max_length=50, null=True)),
                ('specialty', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.IntegerField()),
                ('date', models.DateField()),
                ('signature', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treattt', to='center.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('production_date', models.DateField()),
                ('period_of_guarantee', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('country_of_manfucature', models.CharField(max_length=50)),
                ('company_of_manfucature', models.CharField(max_length=50)),
                ('duration_per_session', models.IntegerField()),
                ('Max_number_per_day', models.IntegerField()),
                ('agent', models.CharField(max_length=50)),
                ('usage_per_day', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('dam', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='center.damage')),
                ('maintenance', models.ManyToManyField(related_name='main', to='center.maintenance')),
            ],
        ),
    ]
