# Generated by Django 4.1.7 on 2023-06-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='id',
            new_name='Id',
        ),
    ]
