# Generated by Django 4.1.7 on 2023-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_rename_id_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='serial',
            field=models.CharField(help_text='Unique ID for this particular book across\xa0whole\xa0library', max_length=50, primary_key=True, serialize=False),
        ),
    ]
