# Generated by Django 4.1.7 on 2023-06-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_alter_maintenance_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='id',
            new_name='deviceid',
        ),
    ]
