# Generated by Django 4.1.7 on 2023-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_rename_id_device_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
