# Generated by Django 4.1.7 on 2023-06-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_alter_therapist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
