# Generated by Django 4.1.7 on 2023-06-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_alter_therapist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceid',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
