# Generated by Django 4.1.7 on 2023-06-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_remove_damage_device_name_remove_device_dam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='device_name',
            new_name='devicess',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='name',
        ),
    ]
