# Generated by Django 4.1.7 on 2023-06-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_rename_device_name_maintenance_devicess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='devicess',
            field=models.ManyToManyField(null=True, related_name='main', to='center.device'),
        ),
    ]
