# Generated by Django 4.1.7 on 2023-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0011_alter_maintenance_devicess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='devicess',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='deevicess',
            field=models.ManyToManyField(null=True, to='center.device'),
        ),
    ]
