# Generated by Django 4.1.7 on 2023-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0016_remove_maintenance_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
