# Generated by Django 4.2 on 2023-06-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0018_alter_damage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
